language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar req roave/security-advisories:dev-master --no-update
  - php composer.phar install

script:
  - php -v
  - vendor/bin/phpcs --standard=psr2 src/ tests/ZendTwig/ tests/Fixture/
  - vendor/bin/phpunit -c tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
